memory.repository.cards = [];
memory.repository.cards.push(new memory.model.Card(1, 'img/bear.png', memory.model.Card.Type.BEAR));
memory.repository.cards.push(new memory.model.Card(2, 'img/bear.png', memory.model.Card.Type.BEAR));
memory.repository.cards.push(new memory.model.Card(3, 'img/bunny.png', memory.model.Card.Type.BUNNY));
memory.repository.cards.push(new memory.model.Card(4, 'img/bunny.png', memory.model.Card.Type.BUNNY));
memory.repository.cards.push(new memory.model.Card(5, 'img/chicken.png', memory.model.Card.Type.CHICKEN));
memory.repository.cards.push(new memory.model.Card(6, 'img/chicken.png', memory.model.Card.Type.CHICKEN));
memory.repository.cards.push(new memory.model.Card(7, 'img/duck.png', memory.model.Card.Type.DUCK));
memory.repository.cards.push(new memory.model.Card(8, 'img/duck.png', memory.model.Card.Type.DUCK));
memory.repository.cards.push(new memory.model.Card(9, 'img/dog.png', memory.model.Card.Type.DOG));
memory.repository.cards.push(new memory.model.Card(10, 'img/dog.png', memory.model.Card.Type.DOG));
